added fixed position to header
captainbrosset/devtools-bug-finder pull request #35
Opened 2017-03-06 19:38 UTC by netoguimaraes

![captura de tela_2017-03-06_16-33-54](https://cloud.githubusercontent.com/assets/11761724/23626296/1ce38400-028b-11e7-8b37-cc61e4f90b7e.png)

The header now has a fixed position, the loader icon is always visible.

fixes #7

2017-03-07 01:28 UTC, nt1m commented
@captainbrosset What do you think ?

2017-03-07 08:04 UTC, captainbrosset requested changes
I like this. Thanks for the PR, that's great!
I have made one comment about a possibly useless property.

Also, I have another comment: how about making the 2 sidebars sticky (or maybe fixed)? So that only the list of bugs scrolls, but you always have access to the filters.

2017-03-07 08:04 UTC, captainbrosset commented on style.css
> +  background-color: #fff;
Is this really needed? I removed it and it looked the same to me.
Also, for info, we have a hidden dark theme. If you click on the title in the header, the site switches to dark. So, if you need to make something white in the future, then remember to also make it black/dark when the dark theme is ON (the class `.dark` is applied to the body when this happens).

2017-03-08 18:38 UTC, netoguimaraes commented
Hey @captainbrosset and @nt1m ,

I've chang some stuff and now the sidebars have position fixed, just the bugs' list is scrolling. I just don't know what to do with the footer, it should be fixed to or what? Please, check it out and send feedback. :smile:

2017-03-09 09:32 UTC, captainbrosset commented
I've tested this. Having the sidebars fixed feels good to me. Thanks!
I think there might be more work required though:

* if you make the window smaller, there comes a point where the sidebars overlaps the bug list:
<img width="744" alt="sidebar1" src="https://cloud.githubusercontent.com/assets/1152698/23743883/94a28184-04b2-11e7-8690-206eb16fa979.PNG">

* If you make the window much larger, the gap between the sidebars and the bug list gets bigger. I think it should always be constant. I think it's 2em now, it would be nice if it stayed at that value:
<img width="740" alt="sidebar2" src="https://cloud.githubusercontent.com/assets/1152698/23743960/d533f35e-04b2-11e7-8095-9e4988189f8b.PNG">

Let me know what you think, and if you have time doing this work.

2017-03-10 14:58 UTC, netoguimaraes commented
Hey @captainbrosset ,

This behaviour when resizing was really bad, but I fixed it with the last commit. I'm thinking about the `main` element `height`, because it was based on sidebars and bug list height, but now, it can only be based on bug list height, because sidebars are fixed and cannot give to `main` element the reference needed, but I will solve it soon. 

Do you have more feedback?

Thanks, anyway.

2017-03-10 17:33 UTC, captainbrosset commented
this looks pretty good! I've tested it and it works really nicely.
Only 2 pieces of feedback I have are:
* the bug list width now depends on its content. So if the title of the bugs is small, then the list will be narrow. If they're long it will be wider. I really think that the list should expand all the way to the right sidebar, always.
* and as you said, the main height is a bit of a problem. If I make the browser smaller than the height of the sidebar, and there aren't many bugs, then I can't scroll the page to see the rest of the sidebar. Only the bug list causes the scrollbar to appear.

Anyway, good work. Let me know what you find next. I haven't reviewed the code changes yet though. Maybe @nt1m wants to do that if he has some time?

2017-03-11 00:38 UTC, nt1m commented
Seems like position: sticky; might be a good way to avoid all these hardcoded values caused by position:fixed;

2017-03-12 05:04 UTC, netoguimaraes commented
Hey @nt1m @captainbrosset , 

I'm using position: sticky; now and it seems to be better. The bug list doesn't depends on its contents anymore and the height problem seems to be solved. Tell me what's next, for me it is pretty good. 
Waiting for feedbacks.

2017-03-15 02:10 UTC, netoguimaraes commented
Up.

2017-03-15 12:09 UTC, nt1m reviewed
Thanks!

2017-03-15 12:09 UTC, nt1m commented on style.css
> +  flex-grow: 100;
Why 100?

2017-03-15 12:09 UTC, nt1m commented on style.css
> +  position: fixed;
The header could also benefit from:

position: sticky;
top: 0;

which gets rid of the other hardcoded values.

2017-03-17 12:06 UTC, netoguimaraes commented on style.css
> +  position: fixed;
It's done;

2017-03-17 12:06 UTC, netoguimaraes commented on style.css
> +  flex-grow: 100;
just 1 solved it, thanks.

2017-03-17 12:08 UTC, nt1m approved these changes
Thanks!

2017-03-17 12:08 UTC, merged